### ISSUE TITLE
Investigate: automated email notification for overdue dishes

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#108]
After a set period of time an automated email should be sent to users regarding overdue dishes

The goal for this task is to determine how this can be accomplished using our current architecture such that requirement [R-9](https://github.com/UofA-Blueprint/DishZero/issues/32) is fulfilled.

A high level design (what systems are required, how do they work, etc) is desired along with an explanation for how it meets the requirements and how it would work

Things to consider:
- What is the trigger mechanism?
- How does it satisfy the ability to be configurable?
- How does it get triggered on the given period?

**Comment by MSNanda515** [comment]
Document discussing the various approaches to the problem:
https://docs.google.com/document/d/1FLVYCplm9n6KPKoPaPoXhlr1DoHaLcjxD_k3xFdBc0Y/edit?usp=share_link
