### ISSUE TITLE
UI/Assets: Import design assets into project

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#142]
Import the design assets (icons/logos) into the project and replace placeholder assets

**Comment by farellukas** [comment]
- In the home screen: there is a button next to the scan QR button (bottom right)
![Image](https://user-images.githubusercontent.com/66014997/214185869-47296f21-d6ad-44df-8e75-f139a66ada94.png)
![Image](https://user-images.githubusercontent.com/66014997/214186046-157c4d33-7637-4a6e-a62b-eadc6fb05fb5.png)

- In the sidebar: there is a "My Dishes" option
![Image](https://user-images.githubusercontent.com/66014997/214186477-390ab960-5601-4b8d-b171-e05e92f704e8.png)
![Image](https://user-images.githubusercontent.com/66014997/214186568-c2344845-cbb0-497f-bf30-507e280b9794.png)

- In the login: there is an image placeholder above the DishZero heading
![Image](https://user-images.githubusercontent.com/66014997/214186807-e1c691a3-7f07-452a-8ad8-ab92f320d73b.png)
![Image](https://user-images.githubusercontent.com/66014997/214186988-e622cb68-b24d-40f5-ace4-c674b036112f.png)

**Comment by MacMalainey** [comment]
I will remove the first and second cases as part of #118 and #85, the last case please fix.
