### ISSUE TITLE
Investigate: Limit credentials to CCID holders only

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#22]
### Description:
Determine how we can limit users to only be able to sign in with their University of Alberta CCIDs while using the Google Auth Provider through Firebase.

Provide code snippets and document process, provide a link to any external documentation or attach it to this Isssue.

### Related story: 
TBD

**Comment by shellbertt** [comment]
Some services that allow you to verify if an email server has a given address:
https://verify-email.org/
https://rapidapi.com/mr_admin/api/email-verifier
https://www.npmjs.com/package/email-check
https://www.npmjs.com/package/legit

However, if we are having people verify their email addresses. Could we just only allow them to go through with this if they use an "@ualberta.ca" email?

**Comment by MacMalainey** [comment]
> Some services that allow you to verify if an email server has a given address, by pinging the mail server: https://verify-email.org/ https://rapidapi.com/mr_admin/api/email-verifier https://www.npmjs.com/package/email-check https://www.npmjs.com/package/legit
> 
> However, if we are having people verify their email addresses. Could we just only allow them to go through with this if they use an "@ualberta.ca" email?

The goal is to be able to use the Google SSO Auth Provider provided by Firebase to authenticate users.

That means that users would sign in through Google and use their ualberta account (think like whenever you see that "sign in with Google" button).

However, normally that functionality will allow users to sign in with any email that is associated with a Google account, here we want to limit users to only those that have the "@ualberta.ca" email (because it is impossible to use the "@ualberta.ca" end on Google SSO and not have it redirect to the Ualberta SSO login page)

**Comment by MacMalainey** [comment]
The goal of this task is to determine how we specifically can limit those users, do we need to perform a check after an attempted login, can we restrict it through the Google Auth platform, can we restrict it using our own UI?

These are all different angles worth investigating to determine which one is the most feasible, cleanest, and safest for both the user and for us

**Comment by farellukas** [comment]
Some resources I found for possible solutions other has thought of. A lot of them involves creating rules in Firebase, but I'm not too familiar with Firebase and how its security rules work (mainly if it only restricts access with people from accessing the database or preventing people without '@ualberta.ca' domains from signing in completely). My plan when I'm free is to try and create a simple test app just to see how they work.

- https://textav.gitbook.io/firebase-react-notes/auth/database-auth/limit-auth-to-certain-domain-only
- https://textav.gitbook.io/firebase-react-notes/auth/google-sign-in/google-sign-in-custom-domain
- https://zachrussell.net/blog/firebase-auth-restrict-login-by-domain/ (this seems to be the most promising and in-depth solution I found, planning to try this out when I'm free).

Just for reference, here are the link to docs for the Firebase security rules and the GoogleAuthProvider API:
- https://firebase.google.com/docs/reference/security/database/#variables
- https://firebase.google.com/docs/reference/js/v8/firebase.auth.GoogleAuthProvider

**Comment by farellukas** [comment]
From what I see as well, there seems to be 2 approach we could take. We could do the CCID checking by the client or by the backend or possibly by both. Personally, I think having it checked by the backend might be more secure, but I would need to do more research on that.

**Comment by farellukas** [comment]
Code snippet:
```javascript
import { getAuth, signInWithPopup, GoogleAuthProvider } from 'https://www.gstatic.com/firebasejs/9.13.0/firebase-auth.js';  // from Firebase Auth

// google authentication
function googleLogin() {
    var provider = new GoogleAuthProvider();
    provider.setCustomParameters({
        hd: 'ualberta.ca'
    });

    const auth = getAuth();

    signInWithPopup(auth, provider)
        .then((result) => {
            // This gives you a Google Access Token. You can use it to access the Google API.
            const credential = GoogleAuthProvider.credentialFromResult(result);
            const token = credential.accessToken;
            // The signed-in user info.
            const user = result.user;
            // ...
            console.log(user);
        }).catch((error) => {
            // Handle Errors here.
            const errorCode = error.code;
            const errorMessage = error.message;
            // The email of the user's account used.
            const email = error.customData.email;
            // The AuthCredential type that was used.
            const credential = GoogleAuthProvider.credentialFromError(error);
            // ...
            console.log(errorCode, errorMessage, email, credential);
        });
}
```
Notes: Calling googleLogin() will launch the UAlberta CCID login popup - use it as an event handler.
