### ISSUE TITLE
Spec: design functionality regarding check-in procedure

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#24]
### Description:

QR Codes are placed on every DishZero Dish

Check-in will occur when a QR code is scanned through the volunteer check-in portal on the website.

Design and document the process using system components when a QR code is scanned (will be scanned in integrated camera)

Document a flowchart diagram showing the steps taken and the components used, clearly indicating:
- [ ] UI Update Events
- [ ] Database checks and updates
- [ ] User input events

### Story:

TODO

**Comment by GurtajK** [comment]
Doc: https://docs.google.com/document/d/1ukgxGx6T1CHvi_r0NbGjeSV4XjeQkWEmoZUgBjJeI58/edit?usp=sharing
