### ISSUE TITLE
Research NFC

### ISSUE THREAD

**Issue by dimassudjito** [UofA-Blueprint/DishZero#4]
Put the finding in google docs in this [folder](https://drive.google.com/drive/u/0/folders/1NkgWJxJSmNdfo_-OIeT6DyGb_mQ0-Zyk) and link it to the software design document.

List of topics:

- Implementation of NFC in react native
- Implementation of NFC in react (web)
- Hardware cost of NFC chip
- Statistics/information about phones that supports NFC 
- How to setup NFC chips
- Outline of how to implement NFC functionalities from start to finish
- Android, IOS, and chrome version that supports NFC
- Verdict

**Comment by MacMalainey** [comment]
Decided to move forwards with QR code
