### ISSUE TITLE
Research Web Vs. Mobile

### ISSUE THREAD

**Issue by dimassudjito** [UofA-Blueprint/DishZero#5]
Put the finding in google docs in this [folder](https://drive.google.com/drive/u/0/folders/1NkgWJxJSmNdfo_-OIeT6DyGb_mQ0-Zyk) and link it to the software design document.

Compared pros and cons of each option

List of topics:

- Web deployment process
- Mobile deployment process (app store and play store)
- Maintainability of web apps (react)
- Maintainability of mobile apps (react native)
- Statistics of people's preference for different kinds of apps
  - hypothesis: people don't like downloading apps
  - hypothesis: people don't like opening website to do something on their phone
- NFC support on the web
  - hypothesis: NFC is not supported on web browser
- QR Code scanner/Camera support on the web
  - hypothesis: the camera is clunky on web browser
- Hardware supported 
  - hypothesis: mobile apps need less powerful hardware to run than web apps
- NEW: How easy to update mobile apps once it's deployed in app store and play store?
- Verdict

**Comment by MacMalainey** [comment]
Verdict: Web deployment

Reasoning: Favor easier deployment, cheaper maintentance, one solution fits all possibility
