### ISSUE TITLE
Admin: Implement algorithm to serialize database dish check-in/out events

### ISSUE THREAD

**Issue by MacMalainey** [UofA-Blueprint/DishZero#81]
We will need to have an algorithm that is able to serialize a range of check-in/out event logs into a CSV format

The range is to be specified by two dates range (inclusive)

The CSV must follow the specified format: TODO

This will be implemented for the admin site, therefore implement the solution using the Firebase Admin SDK.

A fully realized solution (server request etc) need not be created, just a function that is able to build the CSV contents and output them (this will be included in a system we do not have set up yet)

**Comment by farellukas** [comment]
# Dependencies

- Firebase Admin SDK
- File System
- Node CSV

`
// Dependencies
const admin = require("firebase-admin");
const fs = require("fs");
const { stringify } = require("csv-stringify");
`

# Setup for Firebase Admin

`
// Initialize Firebase Admin
var serviceAccount = require("./path-to-private-key.json");
admin.initializeApp({
  credential: admin.credential.cert(serviceAccount),
});
`

More info found here: [Admin SDK](https://firebase.google.com/docs/admin/setup)

# Main code snippet

`
// serializeDatabase()
async function serializeDatabase() {
  // SETUP
  const db = admin.firestore();
  const transactionsRef = db.collection("transactions");
  const filename = "output.csv";
  const writeableStream = fs.createWriteStream(filename); // output stream
  const columns = [
    "timestamp_check_out",
    "taken_by",
    "dish_id",
    "timestamp_check_in",
    "returned_by",
    "condition",
  ];
  const stringifier = stringify({ header: true, columns: columns }); // stringifier stream

  // QUERY TRANSACTIONS
  transactionsRef.get().then((querySnapshot) => {
    // GET ALL TRANSACTIONS DOCS
    let docs = querySnapshot.docs;

    // PROCESS EVERY TRANSACTION DOC
    docs.forEach(async (doc) => {
      // Load secondary docs
      const takenByUserDocSnapshot = await doc.get("user").get();
      const dishesDocSnapshot = await doc.get("dish").get();

      // Extract fields
      const timestampCheckOut = doc.get("timestamp").toDate().toISOString();
      const takenBy = takenByUserDocSnapshot.get("email").split("@")[0];
      const dishId = dishesDocSnapshot.get("id");

      // Returned field
      const returned = doc.get("returned");
      let timestampCheckIn;
      let returnedBy;
      let condition;
      if (returned) {
        if (returned.user) {
          const returnedByUserDocSnapshot = await returned.user.get();
          returnedBy = returnedByUserDocSnapshot.get("email").split("@")[0];
        }
        if (returned.timestamp) {
          timestampCheckIn = returned.timestamp.toDate().toISOString();
        }
        if (typeof returned.broken == "boolean") {
          condition = returned.broken.toString().toUpperCase();
        }
      }

      const row = [
        timestampCheckOut,
        takenBy,
        dishId,
        timestampCheckIn,
        returnedBy,
        condition,
      ];

      stringifier.write(row);
    });
  });

  stringifier.pipe(writeableStream);
  console.log("Finished serializing database");
}
`
